# check_look config

[check_look.npc_fast]
enable = true           # skip all vision/hearing/walls logic, use just basic view value            # default: true
sense_index = 0         # index, starting from 0, of sense for fast check                           # default: 0
fast_from = 2200        # range start of mobs' ProtoIds, from which fast check should kick in       # default: 2200
# fast_to = 65535       # maximum ProtoId for mobs                                                  # default: u16::max_value()

# basic detection distantion value is (basic_bonus + ST_PERCEPTION * basic_perception_rate)

[[check_look.senses]]   # vision
player  = { basic_bonus = 10, basic_perception_rate = 5 }       # basic rates for players
npc     = { basic_bonus = 10, basic_perception_rate = 5 }       # basic rates for nps
self_moving     = { still = 1.0, walking = 1.0, running = 1.0 } # rates which matter when oneself is moving
target_moving   = { still = 1.0, walking = 1.0, running = 1.0 } # rates which matter when target is moving
dir_rate        = [1.0, 0.8, 0.5, 0.4]                          # rate which depends on difference between self direction and direction towards target
# degradation of vision, when line of sight blocked by wall, based on perception - completely blocked, no x-rays for you
wall_rate       = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[[check_look.senses]]   # hearing
player  = {basic_bonus = 5,  basic_perception_rate = 2}         # basic rates for players
npc     = {basic_bonus = 25, basic_perception_rate = 2}         # basic rates for nps
self_moving     = { still = 1.0, walking = 1.0, running = 0.8 } # rates which matter when oneself is moving
target_moving   = { still = 1.0, walking = 1.0, running = 3.0 } # rates which matter when target is moving
dir_rate        = [0.8, 1.0, 0.8, 0.8]                          # rate which depends on difference between self direction and direction towards target
wall_rate       = [     # degradation of hearing, when line of sight blocked by wall, based on perception
    0.1, 0.1, 0.1, 0.1, # perception = [1, 2, 3, 4] 
    0.3, 0.3, 0.3, 0.3, # perception = [5, 6, 7, 8]
    0.4, 0.4,           # perception = [9, 10]
]

[check_look]
map_utility_start = 92  # same as MAP_UTILITY_START from _maps.fos, grants invision between non-gms # default: 92
